# -*- coding: utf-8 -*-
"""Untitled12.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1C5XSybLRGcdmZpqB0AJiKoF63x8kuIbF
"""

import numpy as np
arr_empty = np.empty((2, 3))
print(arr_empty)

import numpy as np
arr_full = np.full((3,2,2), 71)
print(arr_full)

arr = np.linspace(10, -5, 3)
print(arr)

import numpy as np
arr = np.array([2, 1 , 5, 4, 7, 4, 6, 8])
arr = np.sort(arr)
print(arr)

import numpy as np
arr = np.array([[1,4],[3,1]])
arr = np.sort(arr, axis = 0)

print(arr)

import numpy as np
arr = np.array([[1, 5, 2, 3, 0],[4, 6, 7, 8, 9]])
arr = np.sort(arr, axis=0)
print(arr)

import numpy as np

arr = np.array([[[1, 4, 20, 23, 28], 
                 [13, 8, 24, 21, 5]], 
                [[25, 29, 26, 18, 2], 
                 [14, 27, 9, 10, 3]],
                [[19, 15, 11, 22, 0], 
                 [6, 16, 7, 17, 12]]])

arr = np.sort(arr, axis = 0)

print(arr)

arr = np.array([[[1, 4, 20, 23, 28], 
                 [13, 8, 24, 21, 5]], 
                [[25, 29, 26, 18, 2], 
                 [14, 27, 9, 10, 3]],
                [[19, 15, 11, 22, 0], 
                 [6, 16, 7, 17, 12]]])

arr = np.sort(arr, axis = 1)

print(arr)

arr = np.array([[[1, 4, 20, 23, 28], 
                 [13, 8, 24, 21, 5]], 
                [[25, 29, 26, 18, 2], 
                 [14, 27, 9, 10, 3]],
                [[19, 15, 11, 22, 0], 
                 [6, 16, 7, 17, 12]]])

arr = np.sort(arr, axis = 2)

print(arr)

arr = np.array([[[1, 4, 20, 23, 28], 
                 [13, 8, 24, 21, 5]], 
                [[25, 29, 26, 18, 2], 
                 [14, 27, 9, 10, 3]],
                [[19, 15, 11, 22, 0], 
                 [6, 16, 7, 17, 12]]])

arr = np.sort(arr)

print(arr)

import numpy as np

arr = np.array([1, 2, 3, 4, 5])

arr = np.searchsorted([1, 2, 3, 4, 5], 3)

print(arr)

import numpy as np

arr = np.array([1, 2, 3, 4, 5])

arr = np.searchsorted([1, 2, 3, 4, 5], 3, side = 'right')

print(arr)

import numpy as np

arr = np.array([1, 2, 3, 4, 5])

arr = np.searchsorted([1, 2, 3, 4, 5], [-10, 10, 2, 3])

print(arr)

import numpy as np

arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])

arr_concat = np.concatenate((arr1, arr2))

print(arr_concat)

import numpy as np

arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6]])

arr_concat = np.concatenate((arr1, arr2), axis = None)

print(arr_concat)

import numpy as np

arr1 = np.array([[0, 5, 3], [2, 4, 1]])
arr2 = np.array([[0], [1]])

arr_concat = np.concatenate((arr1, arr2), axis = 1)

print(arr_concat)

"""(4, 2), (3, 2)"""

import numpy as np

arr1 = np.array([[2, 5], [3, 0], [1, 7], [6, 4]])
arr2 = np.array([[1, 2], [3, 4], [0, 5]])

arr_concat = np.concatenate((arr1, arr2), axis =None)

print(arr_concat)



"""2,2,5  2,2,4  2"""

arr1 = np.array([[[19, 17, 10, 8, 3], [5, 12, 9, 0, 1]], 
                [[11, 6, 16, 15, 14],[4, 2, 13, 18, 7]]])
arr2 = np.array([[[13, 1, 7, 3], [15, 5, 2, 14]],
                [[4, 12, 11, 10], [8, 6, 9, 0]]])

arr_concat = np.concatenate((arr1, arr2), axis = 2)

print(arr_concat)

import numpy as np
arr_zeros = np.zeros((3, 5, 4), dtype=np.int16)
arr_ones = np.onese((1, 5, 4))
arr_concat = np.concatenate((arr_zeros, arr_ones), axis = 0)
print(arr_concat)

import numpy as np
from PIL import Image
img = np.asarray(Image.open('lena.png'))

img = img.copy()
img2 = img.copy()

img = np.concatenate((img, img2), 0)

img = Image.fromarray(img, 'RGB')
img.save('out.png')


Size = 786432
Ndim= 3
Shape = (512, 512, 3)

arr = np.array([[1, 2, 3, 4,], [5, 6, 7, 8], [9, 10, 11, 12]])
print(arr)

arr = np.array([[1, 2, 3, 4,], [5, 6, 7, 8], [9, 10, 11, 12]])
arr = np.delete(arr, 1, 0)
print(arr)

arr = np.array([[1, 2, 3, 4,], [5, 6, 7, 8], [9, 10, 11, 12]])
arr = np.delete(arr, [1, 3, 5], None)
print(arr)

arr = np.array([[[1, 4, 20], [13, 8, 24]], 
                [[19, 15, 11], [6, 16, 7]]])
arr = np.delete(arr, 0)
print(arr)

arr = np.array([[[1, 4, 20], [13, 8, 24]], 
                [[19, 15, 11], [6, 16, 7]]])
arr = np.delete(arr, (2, 4, 7))
print(arr)

arr = np.array([[[1, 4, 20], [13, 8, 24]], 
                [[19, 15, 11], [6, 16, 7]]])
arr = np.delete(arr, 0, 0)
print(arr)

arr = np.array([[[1, 4, 20], [13, 8, 24]], 
                [[19, 15, 11], [6, 16, 7]]])
arr = np.delete(arr, 1, 0)
print(arr)

arr = np.array([[[1, 4, 20, 13, 28], [13, 8, 24, 21, 5]], 
                [[25, 29, 26, 18, 2], [14, 27, 9, 10, 3]], 
                [[19, 15, 11, 22, 0], [6, 16, 7, 17, 12]]])
arr = np.delete(arr, (0, 1), 2)
print(arr)

import numpy as np

from PIL import Image

img = np.asarray(Image.open('lena.png'))
img = img.copy()

img2 = img.copy()
img= np.delete(img, np.s_[100:300], 0)

img= Image.fromarray(img, 'RGB')

img.save('out.png')

arr = np.array([[[1, 4, 20, 13, 28], [13, 8, 24, 21, 5]], 
                [[25, 29, 26, 18, 2], [14, 27, 9, 10, 3]], 
                [[19, 15, 11, 22, 0], [6, 16, 7, 17, 12]]])
arr.shape

arr1 = np.arange(6)
print(arr1)

arr2 = arr1.reshape(3, 2)
print(arr2)

arr = np.array([[1,2,3], [4, 5, 6]])
arr = np.reshape(arr, (3, -1))
print(arr)

arr1 = np.arange(4)
print(arr1)

arr2 = arr1.reshape(2, 2)
print(arr2)

arr1 = np.arange(7)
print(arr1)

arr2 = arr1.reshape(1, 7)
print(arr2)

arr1 = np.arange(16)
print(arr1)

arr2 = arr1.reshape(4, 4)
print(arr2)

arr1 = np.arange(35)
print(arr1)

arr2 = arr1.reshape(5, 7)
print(arr2)

arr1 = np.arange(10)
print(arr1)

arr2 = arr1.reshape(2, 5)
print(arr2)

arr1 = np.arange(6)
print(arr1)

arr2 = arr1.reshape(3, 2)
print(arr2)

arr1 = np.arange(72)
print(arr1)

arr2 = arr1.reshape(6, 12)
print(arr2)

import numpy as np

arr = np.arange(10).reshape(2, 5)

print(arr)
print(arr[1,3])
print(arr[1, -1])

import numpy as np

arr = np.arange(20).reshape(5, 4)

print(arr)

print(arr[2,3])
print(arr[0:4, 1])
print(arr[:, 1])
print(arr[0:3, :])

import numpy as np

arr = np.arange(42).reshape(6, 7)

print(arr)
print(arr[:,1:4])
print(arr[2:5, :])
print(arr[1:3,:])
print(arr[:,5:7])
print(arr[:, 3:6])
print(arr[1:6,:])
print(arr[0:2,:])
print(arr[:, 1:6])

import numpy as np

arr = np.arange(42).reshape(6, 7)

print(arr[4:6,3:5])
print(arr[1:6,5:7])
print(arr[1:4,0:3])

import numpy as np

arr = np.arange(50).reshape(2, 5, 5)

print(arr)
print(arr[0,2,:])
print(arr[1,:,4])

import numpy as np

arr = np.arange(50).reshape(2, 5, 5)

print(arr)
print(arr[1,0:3,:])
print(arr[0,:,2:4])

import numpy as np

arr = np.arange(50).reshape(2, 5, 5)

print(arr)
print(arr[0,1:4,1:3])
print(arr[1,1:4,0:4])

import numpy as np

arr = np.arange(50).reshape(2, 5, 5)

print(arr[:,0:2,2:4])
print(arr[:,2:5,1:4])

import numpy as np

arr1 = np.arange(20).reshape(4, 5)



print(arr1)

arr2 = np.arange(10,40).reshape(5, 6)
print(arr2)

arr = np.array([[[1], [2], [3]], 
                [[4], [5], [6]]])
print(arr.shape)
arr4 = arr[:, np.newaxis, :, :]
print(arr4.shape)

arr = np.array([1, 2])
print(arr.shape)

arr2 = np.expand_dims(arr, axis=(0,1))
print(arr2)

arr2 = np.expand_dims(arr, axis=0)
print(arr2)
print(arr2.shape)

arr = np.arange(3)
print(arr)

arr1 = arr[:, np.newaxis]
print(arr1)

arr2 = arr[:, np.newaxis] * arr
print(arr2)

arr3 = arr[:, np.newaxis] + arr
print(arr3)

import numpy as np

arr1 = np.array([[1, 1], [2, 2]])

arr2 = np.array([[3, 3], [4, 4]])

arr_vstack = np.vstack((arr1, arr2))
print(arr_vstack)

import numpy as np

arr1 = np.array([[1, 1], [2, 2]])

arr2 = np.array([[3, 3], [4, 4]])
arr_hstack = np.hstack((arr1, arr2))
print(arr_hstack)

arr = np.arange(1, 25).reshape(6, 4)
print(arr)

arr1, arr2, arr3 = np.vsplit(arr, 3)
print(arr1)

print(arr2)

print(arr3)

arr = np.arange(1, 25).reshape(2, 12)
print(arr, "\n")

arr_col1, arr_col2, arr_col3 = np.hsplit(arr, 3)
print(arr_col1)

print(arr_col2)

print(arr_col3)

arr1 = np.array([[0, 1, 2, 3],
                [4, 5, 6, 7],
                [8, 9, 10, 11]])
arr2 = arr1
print(arr2 is arr1)

arr1 = np.array([[0, 1, 2, 3],
                [4, 5, 6, 7],
                [8, 9, 10, 11]])
arr2 = arr1.view()
print(arr2 is arr1)

arr1[0] = 999
print(arr2)
print("\n")
print(arr1)

print(id(arr1))

print(id(arr2))

arr1 = np.array([[0, 1, 2, 3],
                  [4, 5, 6, 7],
                  [8, 9, 10, 11]])
arr2 = arr1.copy()
print(arr1 is arr2)

arr1[0] = 999
print(arr1)

print(arr2)

print(id(arr1))

print(id(arr2))

arr1 = np.array([1, 2])
arr2 = np.ones(2, dtype=int)
print(arr1 + arr2)
print(arr1)
print(arr2)
print(arr1 / arr2)

arr = np.array([1, 2, 3, 4])
print(arr.sum())
arr = np.array([[1, 1], [2, 2]])
print(arr.sum(axis=0))
print(arr.sum(axis=1))

arr = np.array([[4, 2, 5, 7, 2, 7],
                [9, 54, 3, 8, 4, 67],
                [14, 36, 58, 547, 32, 7]])
print(arr.max(axis=0))

print(arr.max(axis=1))

print(arr.max())

arr = np.array([[4, 2, 5, 7, 2, 7],
                [9, 54, 3, 8, 4, 67],
                [14, 36, 58, 547, 32, 7]])
print(arr.mean(axis=0))
print(arr.mean(axis=1))
print(arr.mean())

arr = np.array([[4, 2, 5, 7, 2, 7],
                [9, 54, 3, 8, 4, 67],
                [14, 36, 58, 547, 32, 7]])
print(arr.std(axis=0))
print(arr.std(axis=1))
print(arr.std())

arr = np.array([[4, 2, 5, 7, 2, 7],
                [9, 54, 3, 8, 4, 67],
                [14, 36, 58, 547, 32, 7]])
print(arr.prod(axis=0))
print(arr.prod(axis=1))
print(arr.prod())

arr1 = np.eye(2)
arr2 = np.ones((2, 2)) * 2
print(arr1,'\n')
print(arr2)
print('')
print(arr1.dot(arr2))
print(arr1.dot(arr2).dot(arr2))

arr1 = np.array([[1, 0], [0, 1]])
arr2 = np.array([[4, 1], [2, 2]])
print(np.matmul(arr1, arr2))

import numpy as np
arr = np.array([1.0, 2.0])
print(arr * 1.6)

arr = np.array([[0, 0, 0],
                [10, 10, 10],
                [20, 20, 20],
                [30, 30, 30]])
arr1 = np.array([[0, 1, 2],
                [0, 1, 2],
                [0, 1, 2],
                [0, 1, 2]])
print(arr + arr1)

arr = np.array([[0, 0, 0],
                [10, 10, 10],
                [20, 20, 20],
                [30, 30, 30]])
arr1 = np.array([[0, 1, 2]])
print(arr + arr1)

arr = np.array([[0],
                [10],
                [20],
                [30]])
arr1 = np.array([[0, 1, 2]])
print(arr + arr1)

print(np.random.randint(2, size=10))

print(np.random.randint(5, size=(2, 4)))

print(np.random.rand(3, 2))

print(np.random.randn(2, 4))

arr = np.arange(10)
np.random.shuffle(arr)
print(arr)

arr = np.arange(9).reshape((3, 3))
np.random.shuffle(arr)
print(arr)

print(np.random.choice(5, 3, p=[0.1, 0, 0.3, 0.6, 0]))

zoo = ['rabbit', 'lion', 'elephant', 'monkey']
print(np.random.choice(zoo, 5, p=[0.5, 0.1, 0.1, 0.3]))

arr = np.array([11, 11, 12, 13, 14,
                15, 16, 17, 12, 13, 11, 14, 18, 19, 20])
unique_values = np.unique(arr)
print(unique_values)

unique_values, occurrence_count = np.unique(arr, return_counts = True)
print(occurrence_count)

arr_2d = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12],
                   [1, 2, 3, 4]])
unique_rows = np.unique(arr_2d, axis=0)
print(unique_rows)

arr_2d = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12],
                   [1, 2, 3, 4]])
unique_rows = np.unique(arr_2d, axis=1)
print(unique_rows)

arr_2d = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12],
                   [1, 2, 3, 4]])
unique_value = np.unique(arr_2d)
print(unique_value)

arr = np.arange(4).reshape((2, 2))
print(arr)
print(np.transpose(arr))

arr = np.ones((1, 2, 3))
print(np.transpose(arr, (1, 2, 0)).shape)

"""인덱싱 순서?"""

arr = np.array([[1., 2.], [3., 4.]])
print(arr)
print(arr.T)

arr = np.array([[1., 2., 3., 4.]])
print(arr.T)

