# -*- coding: utf-8 -*-
"""Untitled14.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1y9gcqHcG7frKv4u3Mz7yS0mdqn8Up_yk
"""

import numpy as np

from PIL import Image

img = np.asarray(Image.open('lena.png'))

img = img.reshape(256, 1024, 3)

img = Image.fromarray(img, 'RGB')

img.save('out.png')

import numpy as np
arr = np.ones((1, 2, 3))
print(np.transpose(arr, (1, 0, 2)).shape)



import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
reversed_arr = np.flip(arr)
print(reversed_arr)

import numpy as np
arr_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
reversed_arr = np.flip(arr_2d)
print(reversed_arr)

reversed_arr_cols = np.flip(arr_2d, axis=1)
print(reversed_arr_cols)

reversed_arr_cols = np.flip(arr_2d, axis=0)
print(reversed_arr_cols)

arr = np.array([[1, 2], [3, 4]])
print(arr.flatten())

arr = np.array([[1, 2, 3], [4, 5, 6]])
print(np.ravel(arr))

arr = np.array([1, 2, 3, 4, 5, 6])
np.save("filename", arr)

arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 2, 3, 4, 5, 6])
np.savez( 'file', arr1, arr2)

csv_arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
np.savetxt("new_file.csv", csv_arr)

arr_npy = np.load('./filename.npy')
print(arr_npy)

np.load('./file.npz/')

arr_0 = np.load('./file.npz')['arr_0']
print(arr_0)

arr_txt = np.loadtxt('new_file.csv')
print(arr_txt)

import pandas as pd
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

s = pd.Series([1, 3, 5, 6, 8])
print(s)

s = pd.Series([1, 3, 5, 6, 8], 
index=['하나', '둘', '섯', '넛', '다섯'])
print(s)

list_data = [1, 2, 3, 4, 5]
series = pd.Series(list_data)
print(series)
print('\n')

list_index = ['하나', '둘', '셋', '넷', '다섯']
new_series = pd.Series(list_data, index=list_index)
print(new_series)

dict_data = {'a':1, 'b':2, 'c':3}
sr = pd.Series(dict_data)

print(dict_data)
print('\n')
print(type(sr))
print('\n')
print(sr)

series_data = pd.Series(['홍길동', '26', '010-7777-7777', '광주', '학생'],
                        index = ['이름', '나이', '전화번호', '거주지', '직업'])

num_index_data = series_data[2]
print(num_index_data)

name_index_data = series_data['전화번호']
print(name_index_data)
print('\n')
print('전체 데이터 프레임입니다')
print('\n')
print(series_data)

series_data = pd.Series(['홍길동', '26', '010-7777-7777', '광주', '학생'],
                        index = ['이름', '나이', '전화번호', '거주지', '직업'])

new = series_data[[0, 1, 3]]
print(new)
print('\n')
new = series_data[['이름', '나이', '거주지']]
print(new)

series_data = pd.Series(['홍길동', '26', '010-7777-7777', '광주', '학생'],
                        index = ['이름', '나이', '전화번호', '거주지', '직업'])

new = series_data[2 : 4]
print(new)
print('\n')
new = series_data['전화번호' : '직업']
print(new)

new_series = pd.Series(['welcome', 'to', 'pandas'],
                       index = ['here', 'is', 'Gwangju'])
print(new_series.index)
print(new_series.values)

list_data_2d = [[23, '남', '부산'], [21, '여', '서울'], [25, '남', '광주'],
                [27, '여', '대전'], [24, '여', '광주']]

df = pd.DataFrame(list_data_2d, columns = ['나이', '성별', '지역'])
print(df)
print('\n')

df = pd.DataFrame(list_data_2d,
                  index = ['상우', '지원', '민기', '정민', '수림'],
                  columns = ['나이', '성별', '지역'])
print(df)

dict_data = {'나이' : [23, 21, 25, 27, 24], '성별' : ['남', '여', '남', '여', '여'],
             '지역' : ['부산', '서울', '광주', '대전', '광주']}

df = pd.DataFrame(dict_data)
print(df)
print('\n')

df = pd.DataFrame(dict_data,
                  index = ['상우', '지원', '민기', '정민', '수림'])
print(df)

dict_data = {'나이' : [23, 21, 25, 27, 24], '성별' : ['남', '여', '남', '여', '여'],
             '지역' : ['부산', '서울', '광주', '대전', '광주']}



df = pd.DataFrame(dict_data,
                  index = ['상우', '지원', '민기', '정민', '수림'])
print(df)

test_data = {'팀이름': ['아자아자', '할수있다', 'AI 마피아', 'TF 고수', '경사하강법', '광인사최고'],
             '창의성': ['상', '중', '하', '상', '중', '하'],
             '완성도': [100, 80, 70, 90, 50, 60],
             '사업성': ['좋음', '보통', '부족', '보통', '잘함', '못함']}

df = pd.DataFrame(test_data)
df

print(df['팀이름'])
print('\n')
print(df['사업성'])

print(df.팀이름)
print('\n')
print(df.사업성)
df[['팀이름','사업성']]

test_data = {'팀이름': ['아자아자', '할수있다', 'AI 마피아', 'TF 고수', '경사하강법', '광인사최고'],
             '창의성': ['상', '중', '하', '상', '중', '하'],
             '완성도': [100, 80, 70, 90, 50, 60],
             '사업성': ['좋음', '보통', '부족', '보통', '잘함', '못함']}

df = pd.DataFrame(test_data, index = ['11팀', '12팀', '13팀', '14팀', '15팀', '16팀'])

print(df.loc[['13팀']])
print('\n')
print(df.iloc[[2]])
df
df.loc[['13팀', '14팀']]
df.iloc[[2, 5]]

df.loc['12팀' : '15팀']
df.iloc[1:5]
print('\n')
df.loc['12팀' : :2]
df.iloc[1::2]

test_data = {'이름': ['상우', '현정', '문영', '동엽', '우제'],
             '국어' : [85, 88, 90, 50, 79],
             '수학' : [57, 90, 100, 78, 66],
             '영어' : [85, 89, 67, 98, 98],
             '과학' : [93, 79, 92, 50, 70],
             '체육' : [94, 80, 99, 69, 100]}

df = pd.DataFrame(test_data)
df.set_index('이름', inplace=True)
df
df.loc[['문영'],['영어']]
df.iloc[[2],[2]]

df.loc[['문영'], ['국어', '체육']]
df.iloc[[2], [0, 4]]

df.loc[['문영', '동엽'], ['국어']]
df.iloc[[2, 3], [0]]

df.loc[['문영', '동엽'], ['국어', '체육']]
df.iloc[[2,3], [0,4]]

import pandas as pd
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

test_data = {'이름': ['상우', '현정', '문영', '동엽', '우제'],
             '국어' : [85, 88, 90, 50, 79],
             '수학' : [57, 90, 100, 78, 66],
             '영어' : [85, 89, 67, 98, 98],
             '과학' : [93, 79, 92, 50, 70],
             '체육' : [94, 80, 99, 69, 100]}

df = pd.DataFrame(test_data)
df
df['체육'] = 90
df['사회'] = [89, 69, 70, 80, 100]
df
df.loc[5] = 100

df.loc[6] = ['jack', 90, 91, 92, 93, 94, 95]
df.loc['일곱'] = ['Michael', 71, 72, 73, 74, 75, 76]
df

test_data = {'상호명': ['상우네', '현정이네', '문영이네', '동엽이네', '우제네'],
             '사과': [1000, 900, 1200, 500, 800],
             '배' : [1100, 900, 1000, 1100, 2000],
             '딸기': [800, 900, 600, 900, 1200],
             '포도': [1500, 900, 1000, 800, 900]}
df = pd.DataFrame(test_data)
df

new_df1 = df.set_index('상호명')
new_df1

new_df2 = df.set_index(['사과'])
new_df2

df.set_index(['상호명'], inplace=True)
df

test_data = {'상호명': ['상우네', '현정이네', '문영이네', '동엽이네', '우제네'],
             '사과': [1000, 900, 1200, 500, 800],
             '배' : [1100, 900, 1000, 1100, 2000],
             '딸기': [800, 900, 600, 900, 1200],
             '포도': [1500, 900, 1000, 800, 900]}
df = pd.DataFrame(test_data, index=[4, 2, 1, 0, 3])
df

new_index = [0, 1, 2, 3, 4, 5]

reindex_df1 =df.reindex(new_index)
reindex_df1

reindex_df2 = df.reindex(new_index, fill_value=777)
reindex_df2

test_data = {'상호명': ['상우네', '현정이네', '문영이네', '동엽이네', '우제네'],
             '사과': [1000, 900, 1200, 500, 800],
             '배' : [1100, 900, 1000, 1100, 2000],
             '딸기': [800, 900, 600, 900, 1200],
             '포도': [1500, 900, 1000, 800, 900]}
df = pd.DataFrame(test_data)
df.set_index('상호명', inplace=True)
df

df.reset_index()

test_data = {'상호명': ['상우네', '현정이네', '문영이네', '동엽이네', '우제네'],
             '사과': [1000, 900, 1200, 500, 800],
             '배' : [1100, 900, 1000, 1100, 2000],
             '딸기': [800, 900, 600, 900, 1200],
             '포도': [1500, 900, 1000, 800, 900]}
df = pd.DataFrame(test_data, index=[4, 2, 1, 0, 3])
df
print('\n')

sorted_df = df.sort_index()
sorted_df

ascending_df = df.sort_index(ascending=True)
ascending_df
print('\n')

decending_df = df.sort_index(ascending=False)
decending_df

test_data = {'상호명': ['상우네', '현정이네', '문영이네', '동엽이네', '우제네'],
             '사과': [1000, 900, 1200, 500, 800],
             '배' : [1100, 900, 1000, 1100, 2000],
             '딸기': [800, 900, 600, 900, 1200],
             '포도': [1500, 900, 1000, 800, 900]}
df = pd.DataFrame(test_data)
apple_ascending = df.sort_values(by='사과')
apple_ascending
print('\n')
apple_ascending = df.sort_values(by='사과', ascending=False)
apple_ascending

test_data = {'상호명': ['상우네', '현정이네', '문영이네', '동엽이네', '우제네'],
             '사과': [1000, 900, 1200, 500, 800],
             '배' : [1100, 900, 1000, 1100, 2000],
             '딸기': [800, 900, 600, 900, 1200],
             '포도': [1500, 900, 1000, 800, 900]}
df = pd.DataFrame(test_data)
df.set_index('상호명', inplace=True)
df
print('\n')
ndf1 = df.drop('사과', axis=1)
ndf1
ndf2 = df.drop(['사과', '딸기'], axis=1)
ndf2

ndf1 = df.drop('상우네')
ndf1
ndf2 = df.drop(['현정이네', '문영이네'])
ndf2

df = pd.read_csv('2.csv')
df

data = {'이름' : ['상우', '민철', '민지'],
        '미적' : ['A+', 'B+', 'c'],
        '물리학' : ['c+', 'A+', 'A'],
        'Python' : ['A+', 'B+', 'A+']}
df = pd.DataFrame(data)
df.set_index('이름', inplace=True)
df

df.to_csv('./2.csv')



df = pd.read_json('5.json')
df

data = {'이름' : ['상우', '민철', '민지'],
        '미적' : ['A+', 'B+', 'c'],
        '물리학' : ['c+', 'A+', 'A'],
        'Python' : ['A+', 'B+', 'A+']}
df = pd.DataFrame(data)
df.set_index('이름', inplace=True)
df

df.to_json('./5.json')

dict_data = {'c0' : [1, 2, 3], 'c1' : [4, 5, 6], 
             'c2' : [7, 8, 9], 'c3' : [10, 11, 12], 
             'c4' : [13, 14, 15]}
df = pd.DataFrame(dict_data)

add = df + 10
add
print('\n')

sub = df - 10
sub
print('\n')

mul = df * 10
mul
print('\n')

div = df / 10
div
print('\n')

import numpy as np
data_1 = {'c0' : [1, 2, 3], 'c1' : [4, 5, 6], 
             'c2' : [7, 8, 9], 'c3' : [10, 11, 12], 
             'c4' : [13, 14, 15]}
data_2 = {'c0' : [1, 2, 3], 'c1' : [4, 5, 6], 
             'c2' : [7, 8, 9], 'c3' : [10, 11, 12], 
             'c4' : [13, 14, np.nan]}
df_1 = pd.DataFrame(data_1)
df_2 = pd.DataFrame(data_2)
df_1 + df_2

from random import *

data_1 = []
data_2 = []
for i in range(0, 10):
   data_1.append(uniform(0,1))
for i in range(0, 10):
   data_2.append(uniform(0,2))

dict_data = {'first':data_1, 'second':data_2}
index_data = ['zero', '1st', '2nd', '3rd', '4th', '5th', '6th', '7th', '8th', '9th'] 
df = pd.DataFrame(dict_data, index = index_data)
df

mean_val = df.mean()
first_mean = df['first'].mean()
second_mean = df['second'].mean()

print(mean_val)
print('\n')
print(f'first 평균: {first_mean}')
print(f'second 평균: {second_mean}')

median_val = df.median()
first_median = df['first'].median()
second_median = df['second'].median()

print(median_val)
print('\n')
print(f'first 평균: {first_median}')
print(f'second 평균: {second_median}')

max_val = df.max()

first_max = df['first'].max()

second_max = df['second'].max()

print(max_val)
print('\n')
print(f"first 최댓값:{first_max}")
print(f"second 최댓값: {second_max}")

std_val = df.std()

first_std = df['first'].std()

second_std = df['second'].std()

print(std_val)
print('\n')
print(f"first 최댓값:{first_std}")
print(f"second 최댓값: {second_std}")

data_3 = []
for i in range(0, 10):
  data_3.append(uniform(0, 2))

dict_data = {"first":data_1,
             "second":data_2,
             "third":data_3}
index_data = ['zero', '1st', '2st', '3rd', '4th', 
              '5th', '6th', '7th', '8th', '9th']

ndf = pd.DataFrame(dict_data, index = index_data)
ndf

corr_val =ndf.corr()
corr_val
first_third_corr = ndf[['first, 'third]].corr()
first_third_corr

import seaborn as sns

df = sns.load_dataset('titanic')
df.tail()

nan_df = df['deck'].value_counts(dropna = False)
nan_df

df.head().isnull()

df.head().notnull()

df.isnull().sum(axis=0)

ndf = df.dropna(axis=1, thresh=445)
ndf.columns

ndf2 = ndf.dropna(subset=['age'], how='any', axis=0)
print(ndf2.isnull().sum(axis=0))
print('\n')
print(ndf2.notnull().sum(axis=0))

df.dropna(axis=1, thresh=445, inplace=True)

age_median = df['age'].median(axis=0)
df['age'].fillna(age_median, inplace=True)
df.isnull().sum(axis=0)

data = {'c0': ['a', 'a', 'c', 'd', 'e', 'f', 'c'],
        'c1': [1, 1, 2, 3, 4, 5, 2],
        'c2': [1, 1, 2, 3, 4, 5, 2],
        'c3': ['a', 'a', 'c', 'd', 'e', 'f', 'c']}

df = pd.DataFrame(data)
duplicated_df = df.duplicated()
duplicated_df



corona_df = pd.read_csv('PatientRoute.csv')
print(corona_df.info())
corona_df.head()

corona_df['new_date'] = pd.to_datetime(corona_df['date'])
print(corona_df.info())
corona_df.head()

data = corona_df['new_date'].dt
freq_d = data.to_period(freq='D') 
freq_m = data.to_period(freq='M') 
freq_a = data.to_period(freq='A') 
print(freq_d)
print(freq_m)
print(freq_a)

corona_df['Year'] = corona_df['new_date'].dt.year
corona_df['Month'] = corona_df['new_date'].dt.month
corona_df['Day'] = corona_df['new_date'].dt.day
corona_df.head()

corona_df = pd.read_csv('PatientRoute.csv')
corona_df['new_date'] = pd.to_datetime(corona_df['date'])
corona_df.set_index('new_date', inplace=True)
corona_df

corona_df_ym = corona_df.loc['2020-02']
print(corona_df_ym)
print("\n")

import pandas as pd

with open('html_source.txt', encoding='utf-8') as f:
  temp = f.read()

splitted = temp.split('<div class="inner_number">')
splitted.pop(0)
arr = []

for split in splitted:
  arr.append(split.split('</div>')[0])
pd_arr = pd.Series(arr)

print(pd_arr)

import pandas as pd

with open('html_source.txt', encoding='utf-8') as f:
  temp = f.read()

article_div ='<a class="article"'
del splitted[0] 

splitted = temp.split(article_div)
del splitted[0]
arr = []

for splitdata in splitted:
  print(splitdata)
  arr.append(splitdata.split('</a>')[0].split('>')[-1]
    .replace('\n', '')
    .replace('\t', '')
    .replace(' ', '')
    .strip())



pd_arr = pd.Series(arr)

print(pd_arr)

