# -*- coding: utf-8 -*-
"""0624-1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1k3KTm5DEqiTy17URvKyYB4BN80X6gsK7
"""

import pandas as pd

with open('html_source.txt', encoding='UTF-8') as f:
  temp = f.read()

splitted = temp.split('<div class="inner_number">')
splitted.pop(0)
arr = []

for split in splitted:
  arr.append(split.split('</div>')[0])
pd_arr = pd.Series(arr)

print(pd_arr)

f = open('html_source.txt', 'r', encoding='UTF-8')
source = f.read()
f.close()

splits = source.split('class="article"')
splits.pop(0)
title_list = []

for split in splits:
  title_list.append(split.split('</a>')[0].split('>')[-1]
    .replace('\n/', '')
    .replace('\t/', '')
    .strip())

series = pd.Series(title_list)

print(series)

del(title_list[0])

df = pd.DataFrame({'글번호': pd_arr, '제목': title_list})
df.set_index('글번호', inplace=True)

print(df)

df

f = open('html_source.txt', 'r', encoding='UTF-8')
source = f.read()
f.close()

splits = source.split('<td class="td_name">')
splits.pop(0)
w_list = []

for split in splits:
  w_list.append(split.split('</a>')[0].split('>')[-1]
    .replace('\n/', '')
    .replace('\t/', '')
    .strip())

series = pd.Series(w_list)

print(series)

del(w_list[0])

df = pd.DataFrame({'글번호': pd_arr, '제목': title_list, '글쓴이': w_list})
df.set_index('글번호', inplace=True)

df

f = open('html_source.txt', 'r', encoding='UTF-8')
source = f.read()
f.close()

splits = source.split('<td class="td_date">')
splits.pop(0)
d_list = []

for split in splits:
  d_list.append(split.split('</td>')[0].split('>')[-1]
    .replace('\n/', '')
    .replace('\t/', '')
    .strip())

series = pd.Series(d_list)

print(series)

del(d_list[0])

df = pd.DataFrame({'글번호': pd_arr, '제목': title_list, '글쓴이': w_list})
df.set_index('글번호', inplace=True)

df

f = open('html_source.txt', 'r', encoding='UTF-8')
source = f.read()
f.close()

splits = source.split('<td class="td_view">')
splits.pop(0)
v_list = []

for split in splits:
  v_list.append(split.split('</td>')[0].split('>')[-1]
    .replace('\n/', '')
    .replace('\t/', '')
    .strip())

series = pd.Series(v_list)

print(series)

del(v_list[0])

df = pd.DataFrame({'글번호': pd_arr, '제목': title_list, '글쓴이': w_list, '날짜': d_list, '조회수': v_list})
df.set_index('글번호', inplace=True)

df

f = open('html_source.txt', 'r', encoding='UTF-8')
source = f.read()
f.close()

splits = source.split('<td class="td_likes">')
splits.pop(0)
l_list = []

for split in splits:
  l_list.append(split.split('</td>')[0].split('>')[-1]
    .replace('\n/', '')
    .replace('\t/', '')
    .strip())

series = pd.Series(l_list)

print(series)

del(l_list[0])

df = pd.DataFrame({'글번호': pd_arr, '제목': title_list, '글쓴이': w_list, '날짜': d_list, '조회수': v_list, '좋아요': l_list})
df.set_index('글번호', inplace=True)

df

df





