# -*- coding: utf-8 -*-
"""0624.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ytS0V4uf9AY9jxkd--KP93zXoNQtGe5s
"""

from crawler import CafeCrawler

crawler = CafeCrawler(path='html_source.txt')

print(crawler.generate_dataframe())



print(crawler.filter_view(30, high=40))

print(crawler,filter_date('2021.06.14', high='2021.06.17'))







import matplotlib.pyplot as plt

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline
import matplotlib.pyplot as plt

plt.plot([0, 1, 2], [4, 10, 6])
plt.show

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline
import matplotlib.pyplot as plt
fig = plt.figure()
ax1 = fig.add_subplot(2, 1, 1)
ax2 = fig.add_subplot(2, 1, 2)
plt.show()



fig = plt.figure()
ax1 = fig.add_subplot(1, 2, 1)
ax2 = fig.add_subplot(1, 2, 2)
plt.show()

fig = plt.figure()
ax1 = fig.add_subplot(2, 1, 1)
ax1.plot([1, 2, 3], [4, 5, 6])

ax2 = fig.add_subplot(2, 1, 2)
ax2.plot([1, 10, 100], [1, 100, 10])
plt.show()

fig, ax = plt.subplots(2, 2)

ax[0, 0].plot([1, 2, 3], [4. 10, 6])
ax[0, 1].plot([1, 10, 100], [1. 100, 10])
ax[1, 0].plot([4, 10, 6], [1. 2, 3])
ax[1, 1].plot([1, 100, 10], [1. 10, 100])
plt.show()

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline
import matplotlib.pyplot as plt
import numpy as np

x = np.linspace(0, 15, 1000)
fig, ax = plt.subplots(2, 1)
ax[0].plot(x, np.cos(x))
ax[1].plot(x, np.sin(x))

plt.show()

x = np.linspace(0, 15, 1000)
plt.plot(x, np.cos(x))
plt.plot(x, np.sin(x))

plt.show()

x = np.linspace(0, 15, 1000)

plt.plot(x, np.cos(x), color='red', label='cos')
plt.plot(x, np.sin(x), color='blue', label='sin')

plt.title('Cosine & sine')

plt.xlabel('x label')
plt.ylabel('y label')

plt.legend()

plt.show()

!sudo apt-get install -y fonts-nanm
!sudo fc-cache -fv
!rm ~/,cache/matplotlib -rf

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline
import matplotlib.pyplot as plt
import numpy as np
plt.rc('font', family='NanumBarunGothic')

x = np.arange(0, 10, 1)
plt.scatter(x, x+1)
plt.title('Scatter plot')
plt.show()

x = np.random.normal(100, 20, 300)

plt.boxplot(x)
plt.title('Box Plot')
plt.show()

data = [10, 13, 20, 16]
x= range(len(data))
plt.bar(x, data)
plt.title('Bar Chart')
plt.show()

x = [1, 2, 3, 4, 5]
y = [10, 20, 30, 40, 50]
yerr = [1, 3, 5, 5, 10]
plt.errorbar(x, y, yerr)
plt.title("Error Bar Chart")
plt.show()

import matplotlib.pyplot as plt
import numpy as np

import wave

wav = wave.open("audio.wav", "r")

signal = wav.readframes(-1)
signal = np.frombuffer(signal, np.int16)

plt.plot(signal)
plt.show()

import matplotlib.pyplot as plt
import matplotlib.image as mpimg

img = mpimg.imread('lena.png')

plt.imshow(img)
plt.show()

