# -*- coding: utf-8 -*-
"""0628.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11L3NEWg_BawievcQK5Cw6tyrLgsj8vC9
"""

import tensorflow as tf
mnist = tf.keras.datasets.mnist

(x_train, y_train),(x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10, activation='softmax')
])

model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

model.fit(x_train, y_train, epochs=5)
model.evaluate(x_test, y_test)

import tensorflow as tf
import numpy as np
x = np.array([[1,1],[1,0],[0,1],[0,0]])
y = np.array([[0],[1],[1],[0]])
model = tf.keras.Sequential([
    tf.keras.layers.Dense(units = 2, activation = 'elu', input_shape = (2,)),
    tf.keras.layers.Dense(units = 5, activation = 'elu'),
    tf.keras.layers.Dense(units = 7, activation = 'elu'), 
    tf.keras.layers.Dense(units = 1, activation = 'sigmoid')
    ])

model.compile(optimizer=tf.keras.optimizers.Adam(lR = 0.00),
              loss='mse')
model.fit(x, y, epochs=1000)

"""1. 데이터를 입력하기
2. 모델설계하기
3. 최적화하기
4. 학습하기
학습률이란? Learnig Rate
학습의 속도를 제어하는 상수

"""

print(model.predict(x))

import tensorflow as tf
print(tf.__version__)

fashion_mist = tf.keras.datasets.fashion_mist

(train_x, train_y, (test_x, test_y) = fashoinmist.load_data()
import matplotib.pyplot as plt
 
 plt.imshow(train_x[12])
 plt.show

