# -*- coding: utf-8 -*-
"""0702.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1z5IQ-_1on9V24fHwfNo0uFkymjYQU9Ld
"""

print('Hello World!')

print('|\_/|')
print('|q p|   /}')
print('( 0 )"""\\')
print('|"^"`    |')
print('||_/=\\\__|')

print('강한친구 대한육군')
print('강한친구 대한육군')

print("\    /\\")  
print(" )  ( ')")
print("(  /  )")
print(" \(__)|")

A, B = input('').split()
A, B = int(A), int(B)
print(A+B)

a, b = map(int, input().split())
print(a+b)

a, b = map(int, input().split())
print(a-b)

a, b = map(int, input().split())
print(a*b)

a, b = map(int, input().split())
print(a/b)

a, b = map(int, input().split())
print(a+b)
print(a-b)
print(a*b)
print(int(a/b))
print(a%b)

a, b, c = map(int, input().split())
print((a+b)%c)
print((a%c)+(b%c)%c)
print((a*b)%c)
print((a%c)*(b%c)%c)

a, b, c = map(int, input().split())
print((a+b)%c)
print((a%c + b%c)%c)
print((a*b)%c)
print((a%c * b%c)%c)

a = int(input())
b = input()
print(a * int(b[2]))
print(a * int(b[1]))
print(a * int(b[0]))
print(a * int(b))

A, B = map(int, input().split())

if A > B:
  print('>')
elif A < B:
  print('<')
elif A == B:
  print('==')

a = int(input())

if a >= 90:
  print('A')
elif a >= 80:
  print('B')
elif a >= 70:
  print('C')
elif a >= 60:
  print('D')
else:
  print('F')

a = int(input())
if (a%4 == 0) and (a%100 != 0) or (a%400 == 0):
  print('1')
else:
 print('0')

x = int(input())
y = int(input())
if (x > 0) and (y > 0):
  print('1')
elif (x < 0) and (y > 0):
  print('2')
elif (x < 0) and (y < 0):
  print('3')
elif (x > 0) and (y < 0):
  print('4')
else:
  pass

h, m = map(int, input().split())
if m < 45:
  if h == 0:
    h = 23
    m += 60 
  else:
    h -= 1
    m += 60    
print(h, m-45)

n = int(input())
for i in range(1,10): 
  print(n, '*', i, '=', n * i)

t = int(input())
  for i in range(t): 
    a, b = map(int, input().split())
    print(a+b)

a_list = []
b_list = []
n = int(input())
for i in range(0,n):
  a, b = map(int, input().split())
  a_list.append(a)
  b_list.append(b)

for j in range(0, n):
  print(a_list[j] + b_list[j])

n = int(input())
s = 0
for i in range(1, n+1):
  s += i
print(s)

import sys  
n = int(input())
for i in range(n): 
  a, b = map(int, sys.stdin.readline().split())
  print(a + b)

import sys
T = int(input()) 
for i in range(T):
        a, b = map(int,sys.stdin.readline().split())
        print(a + b)



import sys
num = int(sys.stdin.readline())
for i in range(num):
    a, b = map(int,sys.stdin.readline().split())
    print(a+b)



import numpy as np
x = np.arange(6).reshape([2,3])
x

y = np.arange(12).reshape([3,4])
y

x.dot(y)

