# -*- coding: utf-8 -*-
"""0704.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bKt18C7djUb6ZdOtzF5dp5AmLXtXLH8i
"""

n = int(input())
 
for i in range(n):
    print(i+1)

n = int(input())
for i in range(1, n+1):
    print(i)

n = int(input())
for i in range(n, 0, -1):
    print(i)

a_list = []
b_list = []
n = int(input())
for i in range(0,n):
  a, b = map(int, input().split())
  a_list.append(a)
  b_list.append(b)

for j in range(0, n):
  print(f'Case #{j+1}: {a_list[j] + b_list[j]}')

a_list = []
b_list = []
n = int(input())
for i in range(0,n):
  a, b = map(int, input().split())
  a_list.append(a)
  b_list.append(b)

for j in range(0, n):
  print(f'Case #{j+1}: {a_list[j]} + {b_list[j]} = {a_list[j] + b_list[j]}')

n, x = map(int, input()).split()
a = list.map(int, input().split())
for i in range(n)
  if a[i] < x:
    print(a[i], end ='')

N, X = map(int, input().split())
A = list(map(int, input().split()))
for i in A:
    if i < X:
      return A += i
        print(A)

