# -*- coding: utf-8 -*-
"""0720study.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qdhwDnVas52aCgcYP0LPv5F98ZcFUrCw
"""

# Commented out IPython magic to ensure Python compatibility.
import scipy.stats as st
import matplotlib.pyplot as plt
import numpy as np
# %matplotlib inline

n=10
p=0.5
st.binom.pmf(5, n, p)               # 확률분포.

st.binom.ppf(0.3, n, p)             # 분위수.

# 누적확률.
# P(0 <= x <= 5)
st.binom.cdf(5,n,p)

# 구간의 확률.
# P(3 <= x <=7)
st.binom.cdf(7,n,p )- st.binom.cdf(2,n,p)

"""시각화"""

x=np.arange(0,11)
plt.scatter(x/10, st.binom.ppf(x/10.0,n,p),color='red')
plt.show()

n = 10
p = 0.5
x = np.arange(n+1)
y = st.binom.pmf(x, n, p)
plt.scatter(x, y, color='red', alpha=0.7)
plt.show()

n = 20
p = 0.2
x = np.arange(n+1)
y = st.binom.cdf(x, n, p)
plt.scatter(x, y, color='blue', alpha=0.4)
plt.show()

#코드라이언 기초 파이썬
name = input("이름을 입력해주세요: ")
print(name + "씨 안녕!!")

food1 = input("내가 먹을 음식의 가격 : ")
food2 = input("친구가 먹은 음식의 가격: ")
food1 = int(food1)
food2 = int(food2)
print(food1 + food2)

월세 = int(input("월세를 입력해주세여: "))
관리비 = int(input("관리비를 입력해주세용; "))

print(월세+관리비)
print(월세 - 관리비)
print((월세 + 관리비) * 12)
print(월세 / 관리비)

oders = ['짜장', '짬봉', '탕수육']
oders.append('냉면')
oders.insert(1, '냉면')
oders.insert(3, '양장피')
del oders[0]
oders.remove('짬봉')
print(oders)
print(oders[1])

print(len(oders))

number = [10, 20, 30, 40, 50]

print(number)

name = '안녕하세요 코드라이언입니다.'
len(name)

num = [20, 40, 50, 10 , 30]
print(sum(num))
print(sum(num)/ len(num))
print(max(num))
print(min(num))

menu = {'짜장':4000, '짬뽕': 5000, '탕수육': 9000}

menu['냉면'] = 6000
menu['탕수육'] = 8500
del menu['짜장']
print(menu)
print(menu['짬뽕'])

mygrade = 10
yourgrade = 15
print(mygrade != yourgrade)

myGrade = int(input("학번을 입력하세요 : "))
yourGrade = int(input("학번을 입력하세요 : "))

print(myGrade != yourGrade)

myGrade = int(input("학번을 입력하세요 : "))
yourGrade = int(input("학번을 입력하세요 : "))

if myGrade != yourGrade :
    print("앗 동기네요!")
    print("반갑습니다.")
print("누구세요?")

myGrade = int(input("학번을 입력하세요 : "))
yourGrade = int(input("학번을 입력하세요 : "))

if myGrade == yourGrade :
    print("앗 동기네요!")
else :
    print("앗 동기가 아니네요!")1

myGrade = int(input("학번을 입력하세요 : "))
yourGrade = int(input("학번을 입력하세요 : "))

if myGrade == yourGrade :
    print("안녕하세요 동기님!")
elif myGrade > yourGrade :
    print("안녕하세요 선배님!")
elif myGrade < yourGrade :
    print("안녕하세요 후배님!")
else :
    print("누구세요?")

orders = ["짜장", "짬뽕", "탕수육"]

food = input("먹고싶은 메뉴를 입력해주세요 : ")

if food in orders :
    print("주문할 수 있습니다.")
else :
    print("주문할 수 없습니다.")

menu = {"짜장" : 4000, "짬뽕" : 5000, "탕수육" : 9000}

food = input("먹고싶은 메뉴를 입력해주세요 : ")

if food in menu :
    print(menu[food], "원 입니다.")
else :
    print("주문 불가")

i = 0

while i < 6 :
    print(i)
    i += 1

i = 5

while i >=  0 :
    print(i)
    i -= 1

i = 0
while True :
    print(i)
    i = i + 1

    if i >= 3 :
        print("if문 동작")
        break

print("반복문 종료!")

i = 0 
while i < 10:
  i = i + 1

  if i % 2 == 0:
    continue
  print(i)
  
print('종료')

for x in [10, 20, 30]:
  print('안녕하세요')

for _ in range(5):
  print('안녕하세요')

for _ in range(1, 5, 2):
  print(_)

for _ in range(3, 31, 3):
  print(_)

result = 0

for x in range(1, 101):
  result += x
print(result)

result = 1

for x in range(1, 11):
  result *= x
print(result)

for _ in range(5):
  print('*', end ='')

for _ in range(5):
  print('*'*5)

for _ in range(5):
  print('*'*(_+1))

x = int(input("숫자를 입력해주세요 : "))

for i in range(x) :
    print(i+1)

x = int(input("숫자를 입력해주세요 : "))

for i in range(x, 0, -1) :
    print(i)

x = int(input("숫자를 입력해주세요 : "))

for i in range(x) :
  if i % 10 == 0 :
    print()
  print(i+1, end='\t')   
print()

import random

num = input("게임수: ")

for i in range(0,int(num)):
  lotto = random.sample(range(1, 46), 6)
  lotto.sort()
  print(lotto)

import random

count = int(input("로또를 몇개 구매하시겠습니까? "))

for i in range(count) :
    lotto = random.sample(range(1, 46), 6)
    lotto.sort()
    print(lotto)

print("로또 종료")